- hosts: all # Hosts permitidos
  remote_user: vagrant # Usuario de la máquina
  become: yes # Permitimos el uso de sudo

  # Tareas a realizar
  tasks:
  - name: Actualizar máquina
    command: sudo apt-get update

  - name: Instalar Git
    command: sudo apt-get install -y git

  - name: Instalar pip3
    command: sudo apt-get -y install python3-pip

  - name: Clonar repositorio de GitHub
    git: repo=https://github.com/AGCarlos/IV_1819_Proyecto.git  dest=app/

  - name: Instalar los requisitos del proyecto
    command: pip3 install -r app/requirements.txt
