- hosts: all # Hosts permitidos
  remote_user: vagrant # Usuario de la m치quina
  become: yes # Permitimos el uso de sudo

  # Tareas a realizar
  tasks:

  - name: Instalar aptitude
    apt:
      name: aptitude

  - name: Actualizaci칩n de la m치quina
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 43200

  - name: Instalar paquetes necesarios
    apt: name={{ item }} state=latest
    with_items:
      - git
      - python3-pip

  - name: Instalar Redis-server
    apt: name=redis-server state=latest update_cache=yes

  - name: Comprobar que Redis-server est치 funcionando
    service: name=redis-server state=started

  - name: Clonar repositorio de GitHub
    git: repo=https://github.com/AGCarlos/IV_1819_Proyecto.git  dest=app/

  - name: Instalar los requisitos del proyecto
    command: pip3 install -r app/requirements.txt
